groups:
  - name: nodejs-app-rules
    rules:
      # High CPU Usage
      - alert: HighCPUUsage
        expr: 100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > 80
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is above 80% for instance {{ $labels.instance }}"

      # High Memory Usage
      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is above 85% for instance {{ $labels.instance }}"

      # Application Down
      - alert: ApplicationDown
        expr: up{job="nodejs-app"} == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Node.js application is down"
          description: "The Node.js application has been down for more than 30 seconds"

      # High Response Time
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is above 1 second"

      # High Error Rate
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.05
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "High error rate detected"
          description: "Error rate is above 5% for the last 5 minutes"

      # Database Connection Issues
      - alert: DatabaseConnectionFailure
        expr: nodejs_db_connections_active / nodejs_db_connections_total < 0.5
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Database connection issues"
          description: "Less than 50% of database connections are active"
